
application:
  domain_name: sunyuchao.com  #生产环境

spring:
  datasource:
    # 配置数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf8&useAffectedRows=true&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 123456

  rabbitmq:
    username: guest
    password: guest
    addresses: 127.0.0.1
    listener:
      simple:
        retry:
          max-attempts: 5 #五次之后丢掉消息
          enabled: true
    port: 5673

  elasticsearch:
    rest:
      uris: http://127.0.0.1:9200
  thymeleaf:
    cache: false
  #redis相关
  redis:
    timeout: 2000
    host: 127.0.0.1
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  #邮箱相关
  mail:
    host: smtp.qq.com
    username: 1481232419@qq.com
    password: qnvjkxqaidynbach
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8

logging:
  level:
    classpath:com.syc.blog.mapper: debug
    org.elasticsearch.client.RestClient: ERROR
  config: classpath:config/logback-spring.xml
  file:
    path: $[log.path]