
application:
  zimg_address_url_delete: http://111.229.128.32:4869/admin
  zimg_upload_url: http://111.229.128.32:4869/upload
  zimg_address_url: https://www.sunyuchao.com/files/img/
spring:
  datasource:
    # 配置数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf8&useAffectedRows=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  thymeleaf:
    cache: false
  #redis相关
  redis:
    timeout: 2000
    host: 127.0.0.1
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.springframework.boot.autoconfigure: ERROR  #去掉不用的启动日志
    classpath:com.syc.blog.mapper: debug
  config: classpath:config/logback-spring.xml
  file:
    path: $[log.path]  #logback-spring.xml 取值