
#先从外面走一圈回来，这样zimg接受到的IP是自己的外网IP，不然由于docker原因zimg得到的始终是docker的IP，
#这个IP  172.20.0.1 和nginx查询图片是一样的IP。如果暴露这个IP权限，那么所有人都能访问zimg，不安全
application:
  zimg_upload_url: http://111.229.128.32:4869/upload
  zimg_address_url: https://www.sunyuchao.com/files/img/
  video_upload_url: /docker/video   #映射到服务器的地址，供nginx访问
  video_address_url: https://www.sunyuchao.com/files/video/
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    # 配置数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf8&useAffectedRows=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  elasticsearch:
    rest:
      uris: http://127.0.0.1:9200

  thymeleaf:
    cache: false
    #redis相关
  redis:
    timeout: 2000
    host: 127.0.0.1

logging:
  level:
    org.springframework.boot.autoconfigure: ERROR  #去掉不用的启动日志
    classpath:com.syc.blog.mapper: DEBUG
    org.elasticsearch.client.RestClient: ERROR
  config: classpath:config/logback-spring.xml
  file:
    path: $[log.path]  #logback-spring.xml 取值