version: '3.7'

services:
  blog-core-onlineutils:
    image: java:8
    container_name: blog-core-onlineutils
    volumes:
      - ./app:/data/app
      - ./logs:/data/logs
      - ./qrcode:/data/qrcode
      - ./imgpress:/data/imgpress
      - ./fonts:/usr/share/fonts
    working_dir: /data/app
    command: java -Xms128m -Xmx256m -jar blog-core-onlineutils-service.jar
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8082:8082"
    restart: always
    network_mode: host
